webtalk_init -webtalk_dir C:/Users/ammic/OneDrive/Documents/GitHub/Lab11/Lab11_project/Lab11_project.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 18 13:11:31 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "792d34ee-e760-4dfc-bb34-3bd21904758c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ee0bcc5ab2f64595858c312c0d5347dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "59" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "478 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6076_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1964375504 -regid "" -xml C:/Users/ammic/OneDrive/Documents/GitHub/Lab11/Lab11_project/Lab11_project.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/ammic/OneDrive/Documents/GitHub/Lab11/Lab11_project/Lab11_project.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/ammic/OneDrive/Documents/GitHub/Lab11/Lab11_project/Lab11_project.sim/sim_2/behav/xsim/xsim.dir/guess_FSM_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
